[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-blog_os.json"
rustflags = ["-C", "link-arg=-Ttext=0x700000000000"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
